import { StyleSheet } from 'react-native';

import { IThemeMode } from 'src/actions/coreActions';
import { base, colors, fonts, helpers, themes } from 'src/styles';
import { switchTheme } from 'src/styles/_themes';

export default StyleSheet.create({
  body: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: helpers.cardWidth * 0.7,
  },
  bodyLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'column',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
  },
  bodyRight: {
    alignItems: 'flex-end',
    flexDirection: 'column',
    flexWrap: 'nowrap',
    height: 99,
    justifyContent: 'space-between',
    paddingRight: 16,
    width: 54,
  },
  bonus: {
    alignContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
  },
  boost: {
    alignItems: 'center',
    backgroundColor: colors.redDark,
    borderRadius: 20,
    height: 20,
    justifyContent: 'center',
    left: 10,
    position: 'absolute',
    shadowColor: colors.redLight,
    shadowOffset: {
      height: 4,
      width: 0,
    },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    top: 10,
    width: 20,
    zIndex: 1,
  },
  container: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 10,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    height: 100,
    justifyContent: 'space-between',
    // marginLeft: 15,
    // marginRight: 15,
    position: 'relative',
    width: helpers.cardWidth,
    ...base.shadow,
  },
  iconContainer: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 40,
    height: 80,
    marginLeft: 25,
    overflow: 'hidden',
    width: 80,
  },
  iconHeart: {
    marginTop: 16,
  },
  iconOffers: {
    marginBottom: 16,
  },
  logo: {
    alignSelf: 'center',
    height: 80,
    resizeMode: 'contain',
    width: helpers.cardWidth * 0.3,
    // width: 80,
  },
  logoContainer: {
    // marginLeft: 5,
  },
  logoDark: {
    alignSelf: 'center',
    height: 80,
    resizeMode: 'contain',
    // width: helpers.cardWidth * 0.3,
    width: 80,
  },
  maxBoost: {
    color: '#fff',
    fontSize: 7,
    fontWeight: '500',
    textAlign: 'center',
    width: '100%',
  },
  shadowBox: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.greyLight,
    borderRadius: 10,
    height: 110,
    opacity: 0.1,
    position: 'absolute',
    width: helpers.cardWidth + 2,
  },
  textBonus: {
    color: colors.navy,
    fontFamily: fonts.fontHeading,
    fontSize: 16,
  },
  textBonusBoosted: {
    color: colors.redDark,
    fontFamily: fonts.fontHeading,
    fontSize: 16,
  },
  textOriginal: {
    color: colors.grey,
    fontFamily: fonts.fontRegular,
    fontSize: 12,
    marginRight: 6,
    textDecorationLine: 'line-through',
  },
  textTitle: {
    color: colors.white,
    fontFamily: fonts.fontRegular,
    fontSize: 13,
    marginBottom: 8,
    marginLeft: 5,
    textAlign: 'center',
  },
  textTitleInactive: {
    color: colors.white,
    fontFamily: fonts.fontRegular,
    fontSize: 15,
    marginBottom: 8,
    marginLeft: 5,
    textAlign: 'center',
  },
  textUpto: {
    color: colors.white,
    fontFamily: fonts.fontRegular,
    fontSize: 12,
    marginBottom: 6,
  },
  topContainer: {
    marginLeft: 15,
    marginRight: 15,
    paddingTop: 2,
  },
});
